# Generated by Django 6.1 on 2026-08-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_event_options_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_link',
            field=models.URLField(blank=True, help_text='Link to sign-up form (e.g., Google Forms, Typeform)', null=True),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='rsvp_link',
            field=models.URLField(blank=True, help_text='Link to sign-up form (e.g., Google Forms, Typeform)', null=True),
        ),
    ]
