# Generated by Django 6.1 on 2026-08-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_event_rsvp_link_historicalevent_rsvp_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ABOUT OUR SOCIETY', max_length=200)),
                ('subtitle', models.CharField(default='// SYSTEM ORIGIN &amp; ARCHITECTURE', max_length=200)),
                ('main_heading', models.CharField(default='PIONEERING IT, OPTICS &amp; MEDIA ENGINEERING', max_length=300)),
                ('body_text', models.TextField(default='We are a collective of developers, engineers, and digital artists dedicated to pushing the boundaries of high-performance computing, optics, and broadcast technology.')),
                ('mission_statement', models.TextField(default='To build robust systems, foster open technical education, and explore advanced media production techniques.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
