# Generated by Django 6.1 on 2026-08-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_aboutpagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_category', models.CharField(choices=[('teacher', 'Teacher-in-Charge'), ('committee', 'Committee Member'), ('member', 'General Member')], default='member', max_length=20)),
                ('position', models.CharField(blank=True, help_text='e.g., President, Secretary, Lead Developer', max_length=150, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Profile picture URL', null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which they appear (lower numbers first)')),
            ],
        ),
    ]
