# Generated by Django 6.1 on 2026-08-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome back to GCK Media Control Panel', max_length=200)),
                ('hero_subtitle', models.CharField(default='Manage your systems, media, and events seamlessly.', max_length=300)),
                ('welcome_banner_text', models.TextField(default='System operational and ready for deployment.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Home Page Configuration',
            },
        ),
    ]
