# Generated by Django 6.1 on 2026-08-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_homepagecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='welcome_banner_text',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='badge_text',
            field=models.CharField(default='IT & OPTICAL COMPUTING ARCHITECTURE', max_length=150),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_subtitle',
            field=models.TextField(default='Next-gen platform for IT development, camera engineering, broadcast technology, and high-performance computing systems.'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title',
            field=models.CharField(default='COMPUTING, OPTICS & MEDIA INFRASTRUCTURE', max_length=250),
        ),
    ]
