# Generated by Django 6.1 on 2026-08-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_homepagecontent_welcome_banner_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='Enable to activate maintenance mode across the public site.')),
                ('maintenance_message', models.TextField(default='System undergoing routine kernel update and optical calibration. Standby.', help_text='Message displayed on the maintenance screen.')),
            ],
            options={
                'verbose_name_plural': 'Site Settings & Maintenance Control',
            },
        ),
    ]
