# Generated by Django 6.1 on 2026-08-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='countdown_target',
            field=models.DateTimeField(blank=True, help_text='Target date and time when maintenance mode ends (used for the countdown timer).', null=True),
        ),
    ]
